[project]
name = "reputationscore"
description = "Decentralized reputation tracking"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.reputationscore]
path = "contracts/reputationscore.clar"

[repl.analysis]
passes = ["check_checker"]
